# Generated by Django 3.2.12 on 2022-05-04 13:58

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='User', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UID')),
                ('first_name', models.CharField(default='Jane', max_length=60)),
                ('last_name', models.CharField(default='Doe', max_length=60)),
                ('birth_date', models.DateField(default='01/01/2000')),
                ('address', models.CharField(default='3 Dover ct', max_length=60)),
                ('pcp', models.CharField(default='Cynthia Mann', max_length=60)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('emergency_contacts', models.CharField(default='John Smith', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='UserRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_id', models.IntegerField(choices=[(1, 'Patient'), (2, 'Nurse'), (3, 'Doctor'), (4, 'Admin'), (5, 'Gaurdian')], default=1)),
                ('time_edited', models.TimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=0)),
                ('user', models.ForeignKey(default='temp', on_delete=django.db.models.deletion.CASCADE, to='myapi.user')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_medication', models.CharField(default='NA', max_length=200)),
                ('family_medical_history', models.CharField(default='NA', max_length=200)),
                ('past_medications', models.CharField(default='NA', max_length=200)),
                ('allergies', models.CharField(default='NA', max_length=200)),
                ('medical_history', models.CharField(default='NA', max_length=200)),
                ('user', models.ForeignKey(default='temp', on_delete=django.db.models.deletion.CASCADE, to='myapi.user')),
            ],
        ),
        migrations.CreateModel(
            name='Measurements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(default=98.6)),
                ('blood_pressure', models.CharField(default='120/80', max_length=10)),
                ('pulse', models.IntegerField(default=60)),
                ('blood_oxygen', models.FloatField(default=95.0)),
                ('weight', models.FloatField(default=130.0)),
                ('height', models.CharField(default="5'4", max_length=10)),
                ('user', models.ForeignKey(default='temp', on_delete=django.db.models.deletion.CASCADE, to='myapi.user')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='MRI', max_length=20)),
                ('date_of_purcahse', models.DateField(default='1/1/2000')),
                ('mac', models.CharField(default='AB:12:CD:34:EF:56', max_length=20)),
                ('user_title', models.CharField(default='Doctor', max_length=20)),
                ('firmware_version', models.CharField(default='1.0.0', max_length=10)),
                ('software_version', models.CharField(default='1.0.0', max_length=10)),
                ('user', models.ForeignKey(default='temp', on_delete=django.db.models.deletion.CASCADE, to='myapi.user')),
            ],
        ),
        migrations.CreateModel(
            name='BillingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_company', models.CharField(default='Athem Blue Cross', max_length=60)),
                ('member_id', models.CharField(default='A1B2', max_length=15)),
                ('member_name', models.CharField(default='Jane Doe', max_length=80)),
                ('payment_card_number', models.CharField(default='NA', max_length=16)),
                ('payment_card_expiration', models.DateField(default=datetime.date.today, verbose_name='Expiration Date')),
                ('payment_card_cvv', models.CharField(default='000', max_length=3, verbose_name='CVV')),
                ('billing_address', models.CharField(default='3 Dover ct', max_length=60)),
                ('user', models.ForeignKey(default='temp', on_delete=django.db.models.deletion.CASCADE, to='myapi.user')),
            ],
        ),
    ]
