# Generated by Django 3.2.12 on 2022-03-13 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_villain'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_company', models.CharField(max_length=60)),
                ('member_id', models.CharField(max_length=15)),
                ('member_name', models.CharField(max_length=30)),
                ('saved_credit_cards', models.IntegerField(max_length=20)),
                ('billing_address', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField()),
                ('address', models.CharField(max_length=60)),
                ('pcp', models.CharField(max_length=60)),
                ('sex', models.CharField(max_length=2)),
                ('emergency_contacts', models.CharField(max_length=60)),
            ],
        ),
        migrations.DeleteModel(
            name='Hero',
        ),
        migrations.DeleteModel(
            name='Villain',
        ),
    ]
