# Generated by Django 3.2.12 on 2022-03-13 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_auto_20220313_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billinginfo',
            name='saved_credit_cards',
            field=models.IntegerField(),
        ),
    ]
