# Generated by Django 3.2.12 on 2022-03-13 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_alter_billinginfo_saved_credit_cards'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('date_of_purcahse', models.DateField()),
                ('mac', models.CharField(max_length=20)),
                ('user_title', models.CharField(max_length=20)),
                ('firmware_version', models.CharField(max_length=10)),
                ('software_version', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Measurements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('blood_pressure', models.CharField(max_length=10)),
                ('pulse', models.IntegerField()),
                ('blood_oxygen', models.FloatField()),
                ('weight', models.FloatField()),
                ('height', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delete', models.CharField(max_length=10)),
                ('time', models.TimeField()),
            ],
        ),
    ]
