# Generated by Django 3.2.12 on 2022-03-13 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0005_device_measurements_roles_userroles'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_medication', models.CharField(max_length=200)),
                ('family_medical_history', models.CharField(max_length=200)),
                ('past_medications', models.CharField(max_length=200)),
                ('allergies', models.CharField(max_length=200)),
                ('medical_history', models.CharField(max_length=200)),
            ],
        ),
    ]
