# Generated by Django 3.2.12 on 2022-03-13 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0007_auto_20220313_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billinginfo',
            name='uid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='device',
            name='uid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='measurements',
            name='uid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='uid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='roles',
            name='uid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userroles',
            name='uid',
            field=models.IntegerField(default=0),
        ),
    ]
