# Generated by Django 3.2.12 on 2022-03-13 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0008_auto_20220313_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billinginfo',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='device',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='measurements',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='roles',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='user',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='userroles',
            name='uid',
        ),
    ]
