# Generated by Django 3.2.12 on 2022-03-14 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0009_auto_20220313_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='billinginfo',
            name='uid',
            field=models.CharField(default='user0', max_length=20),
        ),
        migrations.AddField(
            model_name='device',
            name='uid',
            field=models.CharField(default='user0', max_length=20),
        ),
        migrations.AddField(
            model_name='measurements',
            name='uid',
            field=models.CharField(default='user0', max_length=20),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='uid',
            field=models.CharField(default='user0', max_length=20),
        ),
        migrations.AddField(
            model_name='roles',
            name='uid',
            field=models.CharField(default='user0', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='uid',
            field=models.CharField(default='user0', max_length=20),
        ),
        migrations.AddField(
            model_name='userroles',
            name='uid',
            field=models.CharField(default='user0', max_length=20),
        ),
    ]
