# Generated by Django 3.2.12 on 2022-03-16 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0010_auto_20220314_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='Jane', max_length=60),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='Doe', max_length=60),
        ),
        migrations.AlterField(
            model_name='billinginfo',
            name='billing_address',
            field=models.CharField(default='3 Dover ct', max_length=60),
        ),
        migrations.AlterField(
            model_name='billinginfo',
            name='insurance_company',
            field=models.CharField(default='Athem Blue Cross', max_length=60),
        ),
        migrations.AlterField(
            model_name='billinginfo',
            name='member_id',
            field=models.CharField(default='A1B2', max_length=15),
        ),
        migrations.AlterField(
            model_name='billinginfo',
            name='member_name',
            field=models.CharField(default='Jane Doe', max_length=30),
        ),
        migrations.AlterField(
            model_name='billinginfo',
            name='saved_credit_cards',
            field=models.IntegerField(default='0000111122223333'),
        ),
        migrations.AlterField(
            model_name='device',
            name='date_of_purcahse',
            field=models.DateField(default='1/1/2000'),
        ),
        migrations.AlterField(
            model_name='device',
            name='firmware_version',
            field=models.CharField(default='1.0.0', max_length=10),
        ),
        migrations.AlterField(
            model_name='device',
            name='mac',
            field=models.CharField(default='AB:12:CD:34:EF:56', max_length=20),
        ),
        migrations.AlterField(
            model_name='device',
            name='software_version',
            field=models.CharField(default='1.0.0', max_length=10),
        ),
        migrations.AlterField(
            model_name='device',
            name='type',
            field=models.CharField(default='MRI', max_length=20),
        ),
        migrations.AlterField(
            model_name='device',
            name='user_title',
            field=models.CharField(default='Doctor', max_length=20),
        ),
        migrations.AlterField(
            model_name='measurements',
            name='blood_oxygen',
            field=models.FloatField(default=95.0),
        ),
        migrations.AlterField(
            model_name='measurements',
            name='blood_pressure',
            field=models.CharField(default='120/80', max_length=10),
        ),
        migrations.AlterField(
            model_name='measurements',
            name='height',
            field=models.CharField(default="5'4", max_length=10),
        ),
        migrations.AlterField(
            model_name='measurements',
            name='pulse',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='measurements',
            name='temperature',
            field=models.FloatField(default=98.6),
        ),
        migrations.AlterField(
            model_name='measurements',
            name='weight',
            field=models.FloatField(default=130),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='allergies',
            field=models.CharField(default='NA', max_length=200),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='current_medication',
            field=models.CharField(default='NA', max_length=200),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='family_medical_history',
            field=models.CharField(default='NA', max_length=200),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='medical_history',
            field=models.CharField(default='NA', max_length=200),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='past_medications',
            field=models.CharField(default='NA', max_length=200),
        ),
        migrations.AlterField(
            model_name='roles',
            name='role',
            field=models.CharField(default='User', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(default='3 Dover ct', max_length=60),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(default='01/01/2000'),
        ),
        migrations.AlterField(
            model_name='user',
            name='emergency_contacts',
            field=models.CharField(default='John Smith', max_length=60),
        ),
        migrations.AlterField(
            model_name='user',
            name='pcp',
            field=models.CharField(default='Cynthia Mann', max_length=60),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(default='F', max_length=2),
        ),
    ]
